# Generated by Django 4.1.4 on 2023-01-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('weather_conditions', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
